Repository SWPP/ttrs-backend, pull requests merged in 2018-05, with the labels that each got.

#8 Student API
  README.md
  backend/backend/urls.py
  backend/ttrs/permissions.py
  backend/ttrs/serializers.py
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: enhancement

#9 Crawler
  backend/crawler/crawler.py
  backend/ttrs/models.py
Labels: enhancement

#12 Improve validations for student
  backend/ttrs/serializers.py
  backend/ttrs/views.py
Labels: Improvement

#14 Intruduce FilterAPIView and & APIVew of Course, Lecture, College, Department, Major
  backend/ttrs/serializers.py
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: enhancement

#18 Improvement on Crawler; now collects 학문의 영역 for 교양과목
  backend/crawler/crawler.py
  backend/crawler/migrations/0001_initial.py
  backend/crawler/migrations/0002_crawler_cancel_flag.py
  backend/crawler/migrations/0003_auto_20180502_2103.py
  backend/crawler/migrations/0004_auto_20180502_2205.py
  backend/crawler/migrations/0005_auto_20180503_1958.py
  backend/crawler/migrations/0006_auto_20180503_2028.py
  backend/ttrs/migrations/0001_initial.py
  backend/ttrs/migrations/0002_auto_20180502_1439.py
  backend/ttrs/migrations/0003_auto_20180502_1957.py
  backend/ttrs/migrations/0004_auto_20180503_1705.py
  backend/ttrs/models.py
Labels: improvement

#20 Add signin view and separate StudentList and StudentCreate(SignUp)
  backend/ttrs/permissions.py
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: new feature

#29 Lower permissions for views of College, Department and Major
  backend/ttrs/views.py
Labels: improvement

#24 Improvement on Student; new fields
  backend/ttrs/models.py
  backend/ttrs/serializers.py
Labels: improvement

#27 Add Evaluation APIViews & minor fix at Manager/TableView
  backend/manager/views.py
  backend/ttrs/models.py
  backend/ttrs/permissions.py
  backend/ttrs/serializers.py
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: new feature

#37 Improvement on Crawler
  backend/manager/crawler.py
Labels: improvement

#39 bugfix; resolved off-by-one error in Crawler
  backend/manager/crawler.py
Labels: bug

#42 Crawler bugfix
  backend/manager/crawler.py
  backend/manager/serializers.py
Labels: bug

#43 implemented mock recommend func; returns arbitrary tts
  backend/ttrs/recommend.py
  backend/ttrs/serializers.py
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: new feature

#49 delete DetailView of College, Department, Major; Replace same feature with FilterAPIView
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: improvement

#51 implemented test codes
  test/bm_tt_test.py
  test/clean.py
  test/course_test.py
  test/crawler_test.py
  test/evaluation_test.py
  test/lecture_test.py
  test/my_tt_test.py
  test/re_tt_test.py
  test/student_test.py
  test/test.py
  test/test.sh
  test/time_tables_test.py
Labels: new feature

#61 Crawler bugfix
  backend/manager/crawler.py
  backend/ttrs/models.py
Labels: bug

#62 Enable Email Confirmation
  backend/backend/settings.py
  backend/ttrs/templates/acc_active_email.html
  backend/ttrs/tokens.py
  backend/ttrs/urls.py
  backend/ttrs/views.py
Labels: new feature

#63 Introduce Abbreviation Lookup
  backend/manager/views.py
  backend/ttrs/models.py
Labels: new feature

#73 Able to modify not_recommends of Student
  backend/ttrs/recommend.py
  backend/ttrs/serializers.py
Labels: bug fix

#74 Improved API as requested
  backend/ttrs/models.py
  backend/ttrs/recommend.py
  backend/ttrs/serializers.py
  backend/ttrs/views.py
Labels: improvement

#76 Evaluation: author-lecture unique together
  backend/ttrs/models.py
  backend/ttrs/serializers.py
Labels: improvement

#67 Improvement on Recommend
  backend/ttrs/recommend.py
  backend/ttrs/tests.py
Labels: improvement
